// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Login struct {
	Session              string   `protobuf:"bytes,1,opt,name=Session,proto3" json:"Session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Score                int64    `protobuf:"varint,3,opt,name=Score,proto3" json:"Score,omitempty"`
	Head                 string   `protobuf:"bytes,4,opt,name=Head,proto3" json:"Head,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *User) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

type Enter struct {
	RoomId               int32    `protobuf:"varint,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Enter) Reset()         { *m = Enter{} }
func (m *Enter) String() string { return proto.CompactTextString(m) }
func (*Enter) ProtoMessage()    {}
func (*Enter) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *Enter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Enter.Unmarshal(m, b)
}
func (m *Enter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Enter.Marshal(b, m, deterministic)
}
func (m *Enter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Enter.Merge(m, src)
}
func (m *Enter) XXX_Size() int {
	return xxx_messageInfo_Enter.Size(m)
}
func (m *Enter) XXX_DiscardUnknown() {
	xxx_messageInfo_Enter.DiscardUnknown(m)
}

var xxx_messageInfo_Enter proto.InternalMessageInfo

func (m *Enter) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

type UserList struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (m *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(m, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type RoomInfo struct {
	RoomId               int32    `protobuf:"varint,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Login)(nil), "protocol.Login")
	proto.RegisterType((*User)(nil), "protocol.User")
	proto.RegisterType((*Enter)(nil), "protocol.Enter")
	proto.RegisterType((*UserList)(nil), "protocol.UserList")
	proto.RegisterType((*RoomInfo)(nil), "protocol.RoomInfo")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0x31, 0x4b, 0xc4, 0x30,
	0x18, 0x86, 0x49, 0xdb, 0xd4, 0xfa, 0x29, 0x0e, 0x41, 0x24, 0x9b, 0x31, 0x38, 0x64, 0x2a, 0xa2,
	0xe0, 0x3f, 0x10, 0x2c, 0x14, 0x87, 0x14, 0x37, 0x97, 0xda, 0x46, 0x29, 0x5c, 0xf2, 0x1d, 0x49,
	0xef, 0xff, 0x1f, 0x49, 0xdb, 0xbb, 0xe9, 0xa6, 0xbc, 0x0f, 0x6f, 0xf2, 0x84, 0x17, 0x6e, 0x07,
	0xb4, 0x16, 0x5d, 0xbd, 0xf7, 0x38, 0x23, 0xab, 0xd2, 0x31, 0xe0, 0x4e, 0x3e, 0x01, 0x6d, 0xf1,
	0x7f, 0x72, 0x8c, 0xc3, 0x55, 0x67, 0x42, 0x98, 0xd0, 0x71, 0x22, 0x88, 0xba, 0xd6, 0x1b, 0xca,
	0x1f, 0x28, 0xbe, 0x83, 0xf1, 0x8c, 0x41, 0xf1, 0xd5, 0x5b, 0xb3, 0xd6, 0x29, 0xb3, 0x07, 0x28,
	0x63, 0xd7, 0x8c, 0x3c, 0x13, 0x44, 0x51, 0xbd, 0x12, 0xbb, 0x07, 0xda, 0x0d, 0xe8, 0x0d, 0xcf,
	0x05, 0x51, 0xb9, 0x5e, 0x20, 0x1a, 0x3e, 0x4d, 0x3f, 0xf2, 0x62, 0x31, 0xc4, 0x2c, 0x1f, 0x81,
	0x7e, 0xb8, 0xd9, 0xf8, 0xa8, 0xd2, 0x88, 0xb6, 0x19, 0xd3, 0x07, 0x54, 0xaf, 0x24, 0x5f, 0xa0,
	0x8a, 0xd2, 0x76, 0x0a, 0x33, 0x7b, 0x06, 0x7a, 0x08, 0xc6, 0x07, 0x4e, 0x44, 0xae, 0x6e, 0x5e,
	0xef, 0xea, 0x6d, 0x47, 0x1d, 0xaf, 0xe8, 0xa5, 0x94, 0xef, 0x50, 0xa5, 0xb7, 0xee, 0x0f, 0x2f,
	0x59, 0x4f, 0x63, 0xb2, 0xf3, 0x98, 0xdf, 0x32, 0xd9, 0xde, 0x8e, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xd5, 0xa4, 0x3d, 0x8c, 0x2c, 0x01, 0x00, 0x00,
}
